### ISSUE TITLE
Quickstart page overwide

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/security-reviews#44]
This page:
https://ossf.github.io/security-reviews/quickstart.html

is way too wide. It's too wide to see at once on a desktop (Chrome, MacOS) if the browser is windowed (not fullscreen). I haven't fussed through the CSS (style section) to see why.

We should probably also set some simple left/right page margins.

I know there are lots of free CSS templates. Maybe we should snag one, and reference that instead of trying to do inline CSS/style. CSP is best with external CSS & JavaScript, we should probably encourage external CSS anyway :-).

**Comment by dilanbhalla** [comment]
I can work on this!

**Comment by scovetta** [comment]
Thank you!

**Comment by dilanbhalla** [comment]
Just submitted a PR 👍. Window resizing works now, and the interface is a bit different since I used an external CSS template.

The only thing that doesn't work fully is the javascript validation for the package url field. For whatever reason I couldn't get the reportValidity notification to pop up for this case, so I used an alert instead. I'll keep looking into a fix for that.

**Comment by david-a-wheeler** [comment]
I think an alert's fine, so if "fixing that" is endlessly delayed it'd still be fine.

**Comment by scovetta** [comment]
You should be able to do it with this:

```
// Attach this handler to clear the validation whenever someone types in the textarea
$('#packageURLs').on('keyup', function() {
    $('#packageURLs')[0].setCustomValidity('');
    $('#packageURLs')[0].reportValidity();
});

// If you check the contents and they don't look good:
$('#packageURLS')[0].setCustomValidity('No good');
$('#packageURLS')[0].reportValidity();
```

**Comment by dilanbhalla** [comment]
Thanks Mike! Fixed.
